language: node_js
node_js: stable

before_install:
- npm install -g hexo-cli

install: 
- npm install

script: 
- hexo clean
- hexo generate
- export HEXO_ALGOLIA_INDEXING_KEY=149f1eff6b2a1895c3c541c22eec2540
- hexo algolia

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
